# -*- coding: utf-8 -*-
"""Atv MDL 1 - Linguagem de Prog - Pós.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wkqb-2c17pZ5YjAnIxKYIMh_idgCqhV9

Implemente um programa em Python (Python notebook) que constrói um dicionário de termos de um documento (mínimo 1000 palavras) com a frequência de cada termo permitindo confirmar a lei de Zipf para o documento selecionado.  

Comente ao final os resultados obtidos.
"""

import urllib.request  

texto = []

#for line in urllib.request.urlopen('/Biografia_Michael_Jackson.txt'): 
#   texto.append(line.decode('utf-8'))

f = open('/content/Biografia_Michael_Jackson.txt','r', encoding='latin-1')    # para arquivos locais
for line in f:
  texto.append(line)

for i in range(len(texto)):
    texto[i] = texto[i].lower() # para unicidade
    texto[i] = texto[i].replace('\n',' ')
    texto[i] = texto[i].replace('.','')
    texto[i] = texto[i].replace(',','')
    texto[i] = texto[i].replace('(','')
    texto[i] = texto[i].replace(')','')
    texto[i] = texto[i].replace('?','')
    texto[i] = texto[i].replace('\'','') # elimina ' e "
    texto[i] = texto[i].replace('-',' ')

dict = {}                             # crie um dicionário vazio

for line in texto:

  line = line.lower()                   # converte para lower
  words = line.split()                  # separa cada palavra
#  print(words)

  for word in words:                      # para cada palavra em words
    if word not in dict.keys():         # se palavra não está no dicionário 
      dict[word] = 1                    # acrescenta a word com o valor 1
    else:                                 # se a entrada já existe 
      dict[word] =  dict[word] + 1    # apenas soma 1 ao valor já existente

print(dict)

import pandas as pd
import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

df = pd.DataFrame(dict.items(),  columns=['word', 'count']).sort_values('count',ascending=False)
df = df[df['count'] > 4] # somente termos com mais de 4 ocorrências
# df = df.iloc[ np.int(len(df)/2) - 10 : np.int(len(df)/2) + 10 ] # para livros ou textos com muitos termos limita a um número mínimo de termos

plt.figure(figsize=(24,10))
mpl.style.use(['seaborn'])
sns.barplot(x=df.word,y=df['count'])
plt.xticks(rotation=90) 

plt.show()