# -*- coding: utf-8 -*-
"""atv trilha 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-S_WND9b-7HURKOemP5neHamaBJ7u5hl

## **Imports**
"""

import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 
import plotly.express as px

"""###**Import base 1**

A primeira base de dados escolhida foi a relação diplomas emitidos no mês de Outubro do ano de 2022 pela Universidade Federal de Goiás e sua variedade de cursos de Graduação. A escolha se deu por motivos pessoais, já que eu estou nessa lista, dentre os 418 alunos que se formaram neste mês.
"""

diplomas_ufg =  pd.read_csv(r'/content/10-2022.csv', sep=",")
diplomas_ufg = diplomas_ufg.sort_values(by='data_de_ingresso_no_curso', ascending=True)
dados_ufg = diplomas_ufg[['nome_curso_superior', 'data_de_ingresso_no_curso', 'data_da_expedicao_do_diploma']]
dados_ufg = dados_ufg.rename(columns={'nome_curso_superior':'Graduação', 'data_de_ingresso_no_curso':'Data_Matrícula', 'data_da_expedicao_do_diploma':'Data_Formatura'})

"""###**Criando o Gráfico 1**"""

frequencia_cursos = dados_ufg['Graduação'].value_counts()
df = pd.DataFrame(frequencia_cursos)

df.plot.bar(figsize = (12, 8), color='b')

plt.legend(title='Quantidade de formandos por curso')

"""###**Interpretação gráfico 1**

O gráfico acima, gerado a partir da biblioteca matplotlib.pyplot, mostra que o curso de Agronomia foi o curso que mais emitiu diplomas no mês de Outubro, representando mais de 10% da amostragem total (418 formandos), com 44 diplomas; 5 diplomas a mais que o curso de Medicina Veterinária, segundo colocado. Ao todo, 30 cursos formaram alunos no mês de Outubro de 2022, com cursos como Ciências Sociais, Relações Públicas e Letras: Português, formando 1 estudante apenas.

###**Import base 2**

A segunda base foi escolhida devida a importância da doença representada pelos dados. O câncer de ovário atinge mulheres proporcionalmente de acordo com a faixa etária e ainda possui uma taxa de mortalidade considerável. Entretanto, o diagnóstico precoce pode ajudar a proporcionar uma recuperação definitiva.
"""

neopl_ovar =  pd.read_csv(r"/content/A143753187_74_137_21.csv",  sep=";", encoding="ISO-8859-1", on_bad_lines="warn")
neopl_ovar = neopl_ovar.drop(21)

"""###**Criando gráfico 2**"""

plt.figure(figsize=(12,12))
plt.subplot(1, 1, 1)
sns.barplot(x=neopl_ovar.Ano, y=neopl_ovar.Total) 
plt.yticks(range(0, 700, 50))
plt.xlabel('Ano')
plt.ylabel('Casos Notificados')
plt.title('Registros de Neopl malig do ovario - SÃO PAULO - 1997-2017', weight='bold')
plt.show()

"""###**Interpretação gráfico 2**

O grafico acima foi gerado a partir de dados disponibilizados pela Secretaria de Saúde de SP e construído usando a biblioteca seaborn e representa os registros de casos de câncer de ovário no período de 1997 a 2017. A partir da análise do gráfico é possível observar que os registros apresentavam números exorbitantes até o ano de 2015, atingindo seu pico no ano de 2000 com 628 casos no total, daquele ano. A partir do ano de 2016 os registros apresentaram uma queda brusca, com registros de 233 naquele ano e de 136 no ano seguinte.

###**Import base 3**

A terceira e última base escolhida deixa de lado temáticas acadêmicas e de saúde pública, abrangindo um tema mais nerd, visto que mostra a popularidade de jogos de video-games mais vendidos de todos os tempos. Esse mercado sempre foi muito grande e tende a crescer cvada vez mais, com o avanço e disseminação da tecnologia de consoles, computadores e/ ou aparelhos celulares.
"""

video_game =  pd.read_csv(r"/content/List of best-selling video games.csv", sep=",")
#display(video_game)
video_game = video_game[['Rank', 'Title', 'Sales', 'Publisher(s)[a]']]
video_game = video_game[:10]
video_game['Sales'][0] = '238,000,000'
video_game = video_game.rename(columns={'Rank':'RANQUE','Title' : 'NOME', 'Sales': 'VENDAS', 'Publisher(s)[a]': 'Empresa'})

# Substitui a vírgula por ponto na coluna 'VENDAS'
video_game['VENDAS'] = video_game['VENDAS'].str.replace(',', '.')
# Remove os pontos da coluna 'VENDAS'
video_game['VENDAS'] = video_game['VENDAS'].str.replace('.', '')

# Converte a coluna 'VENDAS' para float
video_game['VENDAS'] = video_game['VENDAS'].astype(float)

"""###**Criando gráfico 3**"""

plt.figure(figsize=(12,12))
plt.subplot(1, 1, 1)
sns.barplot(x=video_game.VENDAS, y=video_game.NOME) 
plt.xlabel('Titulo do Jogo')
plt.ylabel('Faturamento em bilhoes U$')
plt.title('Lista dos 10 videogames mais vendidos de todos os tempos', weight='bold')

plt.show()

"""###**Interpretação gráfico 3**

O gráfico acima foi gerado a partir de dados disponibilizados pela plataforma Kaggle e demonstra os 10 jogos de videogame que mais geraram lucro, em vendas. A tabela contém a relação de 49 jogos; portanto, para a amostragem no gráfico não ficar tão grande, e a visualização ficar mais intuitiva, durante a fase de tratamento de dados, foi filtrado somente o top 10. O jogo 'Minecraft' demonstra o melhor lucro, com uma margem grande de diferença do segundo colocado 'GTA V'.

###**Criando gráfico 4**
"""

frequencia = video_game['Empresa'].value_counts()
frequencia_games = pd.DataFrame(frequencia)

frequencia_games.plot(figsize = (10, 6), color='g', yticks=range(0,5,1))
plt.xticks(rotation='vertical')

plt.legend(title='Empresas que mais aparecem no top 10')

"""###**Interpretação gráfico 4**

O gráfico acima foi gerado a partir da mesma base de dados do gráfico 3, com o auxílio da biblioteca matplotlib e demonstra a frequência das empresas que desenvolvem os jogos. Portanto, é possível observar que a empresa Nintendo é a que mais aparece no top 10, com 4 jogos, seguido pela Rockstar Games, com 2 jogos. As outras empresas empatam, com apenas uma aparição, dentre elas a Xbox Game Studios, que aparece no topo da lista de faturamento, com o jogo Minecraft.
"""